config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true, length: {maximum: 200}
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true, length: {maximum: 200}
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @new_book_comment = current_user.book_comments.new(book_comment_params)
    @new_book_comment.book_id = @book.id
    @new_book_comment.save
    redirect_to request.referer
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @new_book = Book.new
    @books = Book.all
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:create_book] = "You have created book successfully."
      redirect_to book_path(@new_book.id)
    else
      # renderの場合、indexアクションを通らず@userが空になる。したがって改めて定義する。
      # @new_book, @booksも同様
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @new_book_comment = BookComment.new
    @book_comments = BookComment.where(book_id: params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.update(book_params)
      flash[:update_book] = "You have updated book successfully."
      redirect_to book_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    # 同じページをリダイレクト
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @new_book = Book.new
    @user = User.find(current_user.id)
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:user_update] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_user_info.html.erb
<!--nameが変数-->
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

app/views/books/edit.html.erb
<main>
  <p class="notion"></p>
  <div class="container">
    <% if @book.errors.any? %>
    <div class="error_explanation">
      <ul class="alert alert-danger" role="alert">
      <h6 class="alert-heading">
      <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h6>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </ul>
    </div>
    <% end %>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <div class="form-group" >
          <label for="inputTitle">Title</label>
          <%= f.text_field :title, autofocus: true, id:"inputTitle", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="inputBody">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"inputBody", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <% if @new_book.errors.any? %>
    <div class="error_explanation">
      <ul class="alert alert-danger" role="alert">
      <h6 class="alert-heading">
      <%= @new_book.errors.count %> errors prohibited this obj from being saved:
      </h6>
      <ul>
      <% @new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    </div>
    <% end %>
    <div class="row">
      <!--userのshowページの左側-->
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100, 100) %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control", rows:"3" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
      <!--userのshowページの右側-->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete, class:"text-danger" do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post, class:"text-primary" do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数：<%= book.book_comments.count %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <% if @new_book_comment.errors.any? %>
    <div class="error_explanation">
      <ul class="alert alert-danger" role="alert">
      <h6 class="alert-heading">
      <%= @new_book_comment.errors.count %> errors prohibited this obj from being saved:
      </h6>
      <ul>
      <% @new_book_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <!--userのshowページの左側-->
      <div class="col-md-3">
        <%= render 'user_info', user: @user %>
        <div class="row">
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control", rows:"3" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
      <!--userのshowページの右側-->
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= image_tag @book.user.get_profile_image(100, 100) %>
                  <br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete, class:"text-danger" do %>
                      <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post, class:"text-primary" do %>
                      <i class="fa-solid fa-heart"></i><%= @book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数：<%= @book.book_comments.count %></p>
              </td>
              <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger" %>
              </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div class="col-md-11 ml-auto">
          <h3>Comments</h3>
          <% if @book.book_comments.count == 0 %>
            <div class="row">
              <div class="col-md-11 ml-auto">
                <h5>No comments</h4>
              </div>
            </div>
          <% end %>
          <table class="table">
            <% @book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user.id) do %>
                  <%= image_tag book_comment.user.get_profile_image(80, 80) %>
                  <br>
                  <%= book_comment.user.name %>
                <% end %>
              </td>
              <td>
                <p><%= book_comment.comment %></p>
              </td>
              <% if book_comment.user == current_user %>
              <td>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn btn-sm btn-danger" %>
              </td>
              <% end %>
            </tr>
            <% end %>
          </table>
          <%= form_with model: [@book, @new_book_comment] do |f| %>
          <div class="form-group">
            <label for="new_book_comment_comment">コメントを投稿する（1文字以上）</label>
            <%= f.text_area :comment, rows: '5', class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit '送信', class:"btn btn-success" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <span><i class="fas fa-book"></i></span>Bookers!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <span><i class="fas fa-book"></i></span><strong>Bookers</strong> !!</h1>
        <p>In <span><i class="fas fa-book"></i></span><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
          </div>
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f083d48cc8.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="mb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= user_path(current_user.id) %>><span><i class="fas fa-home"></i></span> Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= users_path %>><span><i class="fas fa-users"></i></span> Users</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= books_path %>><span><i class="fas fa-book-open"></i></span> Books</a>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <span><i class="fas fa-sign-out-alt"></i></span> Log out
                <% end %>
                <!--<a class="nav-link text-light" href=<%= destroy_user_session_path %>><span><i class="fas fa-sign-out-alt"></i></span> Log out</a>-->
              </li>
              <% else %>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= root_path %>><span><i class="fas fa-home"></i></span> Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= about_path %>><span><i class="fas fa-link"></i></span> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= new_user_registration_path %>><span><i class="fas fa-user-plus"></i></span> Sign up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href=<%= new_user_session_path %>><span><i class="fas fa-sign-in-alt"></i></span> Log in</a>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container px-5 px-sm-0">
      <% flash.each do |key, value| %>
        <p><%= content_tag(:div, value, class: "#{key}") %></p>
      <% end %>
    </div>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id="notion">
  </p>
  <div class="container">
    <% if @user.errors.any? %>
    <div class="error_explanation">
      <ul class="alert alert-danger" role="alert">
      <h6 class="alert-heading">
      <%= @user.errors.count %> errors prohibited this obj from being saved:
      </h6>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </ul>
    </div>
    <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class:"form-control-file" %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <!--userのshowページの左側-->
      <div class="col-md-3">
        <%= render 'books/user_info', user: @user %>
        <div class="row">
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control", rows:"3" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
      <!--userのshowページの右側-->
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100, 100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <!--userのshowページの左側-->
      <div class="col-md-3">
        <%= render 'books/user_info', user: @user %>
        <div class="row">
          <%= link_to edit_user_path(params[:id]), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control", rows:"3" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          </div>
        <% end %>
      </div>
      <!--userのshowページの右側-->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :delete, class:"text-danger" do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(book), method: :post, class:"text-primary" do %>
                      <i class="fa-solid fa-heart"></i><%= book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                <p>コメント数：<%= book.book_comments.count %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>